# Generated by Django 5.0.4 on 2024-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/Notfoundimage.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
